
[dependencies]
  fastly = "^0.8.2"
  serde_json = "1.0.59"
[package]
  edition = "2021"
  name = "rust-redirects-usecase"
  publish = false
  version = "0.1.0"

[profile]

  [profile.release]
    debug = 1
